### ISSUE TITLE
DIA: Piney Point Water Quality Complete Analysis

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/csda-piney-point-waterquality#1]
### **Description**
The research will focus on studying algal blooms/chlorophyll a detection following a wastewater leak into Tampa Bay from the old Piney Point phosphate plant using DESIS hyperspectral imagery. 

[Notes](https://docs.google.com/document/d/1g2vJN1BMuXXlHLozG9KxOFyz3VqHJzIpP7IJ99Q1KZA/edit#heading=h.5xp0tsyritd1)
[Data](https://drive.google.com/drive/folders/1Q7OdsK9LTND7de_VWSnDBnaRp7OuDSmp)
[DIA](https://docs.google.com/document/d/1ZWfVdB7aFi1KqIqRB6Fg4OfxotHTrQwP0RLt-3p8ewY/edit)

### **Tasks:**
- [x] Create chl-a maps using regression equation and threshold values
- [x] Validate with ground truth data
- [ ] ~Test model predictions using small separate AOI~

### **Acceptance criteria**
- [x] Analysis is completed and have results

### **Demo**
Initial results can be demonstrated
