### ISSUE TITLE
DIA: Piney Point Write-up

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/csda-piney-point-waterquality#2]
### **Description**
The research will focus on studying algal blooms/chlorophyll a detection following a wastewater leak into Tampa Bay from the old Piney Point phosphate plant using DESIS hyperspectral imagery. 

[Notes](https://docs.google.com/document/d/1g2vJN1BMuXXlHLozG9KxOFyz3VqHJzIpP7IJ99Q1KZA/edit#heading=h.5xp0tsyritd1)
[Data](https://drive.google.com/drive/folders/1Q7OdsK9LTND7de_VWSnDBnaRp7OuDSmp)
[DIA](https://docs.google.com/document/d/1ZWfVdB7aFi1KqIqRB6Fg4OfxotHTrQwP0RLt-3p8ewY/edit)

### **Tasks:**
- [x] Write draft DIA (in progress)
- [x] Coordinate sections with Sid
- [ ] ~Subit DIA for review~

### **Acceptance criteria**
- [x] draft complete
