### ISSUE TITLE
DIA: water quality draft

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/csda-piney-point-waterquality#3]
### Description
The first draft of the water quality DIA is complete: https://docs.google.com/document/d/1aB8D4TS_TZh7kZT6RBopAX1EXoNacUDP5nv4_aD12mU/edit#heading=h.dx6vyrw2va4z

This ticket is for the remaining tasks to get this submitted.

### Tasks
- [x] we need a figure with chl-a maps. Not sure what threshold values Sid was using before ([this doc](https://docs.google.com/document/d/1kdmhDTso_IMK6PpDX3zcYHU-53uGD4LiEIuj3nETy_0/edit))
- [x] Sid needs to review/edit
- [x] Brad/Sid make some iterations

### Acceptance Criteria
- [x] submit to DIA

**Comment by hbparache** [comment]
Drafted, waiting for @siddharth0248
